name: Hello World
author: ilhan
description: Some description 
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: ilhan 
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint:
  args:  
    - ${{ input.who-to-greet }}
